Repository devdynam0507/picker, pull requests merged in 2022-03, with the labels that each got.

#59 로딩화면 로직 개선, 컴포넌트화
  src/Components/LoadingBottom.jsx
  src/Components/LoadingTop.jsx
  src/Components/Map.jsx
  src/pages/Category/Category.jsx
  src/pages/Home/Home.jsx
  tailwind.config.js
Labels: Client, E-1.5h

#60 디자인 수정, 애니메이션 추가
  src/Components/Button.jsx
  src/Components/LoadingBottom.jsx
  src/Components/LoadingTop.jsx
  src/Components/Main.jsx
  src/pages/Home/Home.jsx
  tailwind.config.js
Labels: Client, E-3h

#63 fix: api 주소 변경, package.json 프록시 변경
  package.json
  src/Utils/CommUtils.js
  src/pages/Home/Home.jsx
  yarn.lock
Labels: Client, E-1h

#64 [PR] 윈도우 환경 이슈 해결
  package-lock.json
  public/food/chicken.png
  public/food/cn.png
  public/food/jp.png
  public/food/kr.png
  public/food/meat.png
  public/food/midnightsnack.png
  public/food/pizza.png
  public/food/ramen.png
  public/food/tteokbokki.png
  src/Components/Main.jsx
  src/pages/Home/Home.jsx
  yarn.lock
Labels: Complete, Client, E-2h
